### ISSUE TITLE
[EPIC] Implement all TR1 state input/behaviour handlers

### ISSUE THREAD

**Issue by stohrendorf** [stohrendorf/EdisonEngine#11]
- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [x] 12
- [x] 13
- [x] 14 - Grab to Fall
- [x] 15
- [x] 16
- [x] 17
- [x] 18
- [x] 19
- [x] 20
- [x] 21 - Step Right
- [x] 22 - Step Left
- [x] 23
- [x] 24
- [x] 25
- [x] 26
- [x] 27
- [x] 28
- [x] 29
- [x] 30
- [x] 31
- [x] 32
- [x] 33 - On Water Stop
- [x] 34 - On Water Forward
- [x] 35 - Underwater Diving
- [x] 36 - Pushable Push
- [x] 37 - Pushable Pull
- [x] 38 - Pushable Grab
- [x] 39 - Pick Up
- [x] 40 - Switch Down
- [x] 41 - Switch Up
- [x] 42 - Insert Key
- [x] 43 - Insert Puzzle
- [x] 44
- [x] 45
- [x] 46 - Boulder Death
- [x] 47 - On Water Backward
- [x] 48 - On Water Left
- [x] 49 - On Water Right
- [x] 50 - Use Midas
- [x] 51 - Midas Death
- [x] 52
- [x] 53
- [x] 54
- [x] 55 - On Water Exit
